### ISSUE TITLE
Change docs for new optional Spark service in Watson Studio

### ISSUE THREAD

**Issue by scottdangelo** [IBM/kafka-streaming-click-analysis#29]
Watson Studio notebooks now require adding the Spark service on a project basis.
These docs need to be changed for this.
see:
https://github.ibm.com/IBMCode/howtos/pull/311

**Comment by xwu0226** [comment]
@ScrapCodes Can you take a look at this issue?

**Comment by stevemart** [comment]
@ScrapCodes we checked a few weeks ago and it was not added by default, we had to create a spark service after creating the project and then associate it with the project. We documented the steps for a general use case here: https://developer.ibm.com/code/howtos/create-a-spark-service-for-ibm-watson-studio but ask that the code patterns be maintained and also document the steps. They don't need to match the link exactly, but some indication to the user would be very helpful.

**Comment by ScrapCodes** [comment]
Ahh, looks like this is true when we create a new project.
